# Generated by Django 2.2.4 on 2019-12-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0006_networkvisualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkvisualization',
            name='betweenness_centrality',
            field=models.ImageField(upload_to='network_visualization'),
        ),
        migrations.AlterField(
            model_name='networkvisualization',
            name='closeness_centrality',
            field=models.ImageField(upload_to='network_visualization'),
        ),
        migrations.AlterField(
            model_name='networkvisualization',
            name='clustering_coefficient',
            field=models.ImageField(upload_to='network_visualization'),
        ),
        migrations.AlterField(
            model_name='networkvisualization',
            name='degree_centrality',
            field=models.ImageField(upload_to='network_visualization'),
        ),
        migrations.AlterField(
            model_name='networkvisualization',
            name='eigenvector_centrality',
            field=models.ImageField(upload_to='network_visualization'),
        ),
        migrations.AlterField(
            model_name='networkvisualization',
            name='visualization',
            field=models.ImageField(upload_to='network_visualization'),
        ),
    ]
