# Generated by Django 2.2.4 on 2019-12-18 12:25

from django.db import migrations, models
import socialife.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0007_auto_20191217_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='betweenness_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to=socialife.models.MyUser.user_directory_path),
        ),
        migrations.AddField(
            model_name='myuser',
            name='closeness_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to=socialife.models.MyUser.user_directory_path),
        ),
        migrations.AddField(
            model_name='myuser',
            name='clustering_coefficient',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to=socialife.models.MyUser.user_directory_path),
        ),
        migrations.AddField(
            model_name='myuser',
            name='degree_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to=socialife.models.MyUser.user_directory_path),
        ),
        migrations.AddField(
            model_name='myuser',
            name='eigenvector_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to=socialife.models.MyUser.user_directory_path),
        ),
    ]
