# Generated by Django 2.2.4 on 2019-12-19 03:57

from django.db import migrations, models
import socialife.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0008_auto_20191218_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='betweenness_centrality',
            new_name='in_betweenness_centrality',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='closeness_centrality',
            new_name='in_closeness_centrality',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='clustering_coefficient',
            new_name='in_degree_centrality',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='degree_centrality',
            new_name='in_eigenvector_centrality',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='eigenvector_centrality',
            new_name='out_betweenness_centrality',
        ),
        migrations.RemoveField(
            model_name='networkvisualization',
            name='ba',
        ),
        migrations.RemoveField(
            model_name='networkvisualization',
            name='betweenness_centrality',
        ),
        migrations.RemoveField(
            model_name='networkvisualization',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='networkvisualization',
            name='cca',
        ),
        migrations.RemoveField(
            model_name='networkvisualization',
            name='closeness_centrality',
        ),
        migrations.RemoveField(
            model_name='networkvisualization',
            name='da',
        ),
        migrations.RemoveField(
            model_name='networkvisualization',
            name='degree_centrality',
        ),
        migrations.RemoveField(
            model_name='networkvisualization',
            name='ea',
        ),
        migrations.RemoveField(
            model_name='networkvisualization',
            name='eigenvector_centrality',
        ),
        migrations.AddField(
            model_name='myuser',
            name='out_closeness_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to=socialife.models.MyUser.user_directory_path),
        ),
        migrations.AddField(
            model_name='myuser',
            name='out_degree_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to=socialife.models.MyUser.user_directory_path),
        ),
        migrations.AddField(
            model_name='myuser',
            name='out_eigenvector_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to=socialife.models.MyUser.user_directory_path),
        ),
        migrations.AddField(
            model_name='networkvisualization',
            name='in_betweenness_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to='network_visualization'),
        ),
        migrations.AddField(
            model_name='networkvisualization',
            name='in_closeness_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to='network_visualization'),
        ),
        migrations.AddField(
            model_name='networkvisualization',
            name='in_degree_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to='network_visualization'),
        ),
        migrations.AddField(
            model_name='networkvisualization',
            name='in_eigenvector_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to='network_visualization'),
        ),
        migrations.AddField(
            model_name='networkvisualization',
            name='out_betweenness_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to='network_visualization'),
        ),
        migrations.AddField(
            model_name='networkvisualization',
            name='out_closeness_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to='network_visualization'),
        ),
        migrations.AddField(
            model_name='networkvisualization',
            name='out_degree_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to='network_visualization'),
        ),
        migrations.AddField(
            model_name='networkvisualization',
            name='out_eigenvector_centrality',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to='network_visualization'),
        ),
        migrations.AlterField(
            model_name='networkvisualization',
            name='clustering_coefficient',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to='network_visualization'),
        ),
        migrations.AlterField(
            model_name='networkvisualization',
            name='visualization',
            field=models.ImageField(default='media/avatar/Visualization.png', upload_to='network_visualization'),
        ),
    ]
