# Generated by Django 2.2.4 on 2019-12-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0009_auto_20191219_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='in_betweenness_centrality',
            new_name='betweenness_centrality',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='in_closeness_centrality',
            new_name='closeness_centrality',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='in_eigenvector_centrality',
            new_name='clustering_coefficient',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='out_betweenness_centrality',
            new_name='eigenvector_centrality',
        ),
        migrations.RenameField(
            model_name='networkvisualization',
            old_name='in_betweenness_centrality',
            new_name='betweenness_centrality',
        ),
        migrations.RenameField(
            model_name='networkvisualization',
            old_name='in_closeness_centrality',
            new_name='closeness_centrality',
        ),
        migrations.RenameField(
            model_name='networkvisualization',
            old_name='in_eigenvector_centrality',
            new_name='eigenvector_centrality',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='out_closeness_centrality',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='out_eigenvector_centrality',
        ),
        migrations.RemoveField(
            model_name='networkvisualization',
            name='out_betweenness_centrality',
        ),
        migrations.RemoveField(
            model_name='networkvisualization',
            name='out_closeness_centrality',
        ),
        migrations.RemoveField(
            model_name='networkvisualization',
            name='out_eigenvector_centrality',
        ),
    ]
